### ISSUE TITLE
Multiple profiles on histograms

### ISSUE THREAD

**Issue by low-sky** [Astroua/CARTAvis#133] opened 2016-01-31 02:56 UTC
In reviewing the v0.5 viewer, I found that the histogram profile appears to be drawing one profile per channel of the cube.  For the `orion_12co_hera.fits` file, I get a screenshot that looks like this:

![screen shot 2016-01-30 at 19 48 39](https://cloud.githubusercontent.com/assets/1139910/12699918/5b6f837c-c78b-11e5-9c2b-25404f7033e0.png)

This represents a change in the behaviour that I don't think is intended.  Is this a product of trying to improve histogram performance?

@slovelan @astrilet

**Comment by low-sky** [comment] 2016-01-31 03:00
Possibly related, the colour maps in histograms don't update when the image colour map is updated.

![screen shot 2016-01-30 at 19 59 01](https://cloud.githubusercontent.com/assets/1139910/12699933/01a6fb44-c78c-11e5-95d8-b5ecdb8224e4.png)

**Comment by slovelan** [comment] 2016-02-01 21:07
I was unable to reproduce the multiple channel problem on my local build so it should be fixed at my next check-in.

I was able to reproduce and fix the color problem.  It should be fixed with my next check-in.

**Comment by low-sky** [comment] 2016-02-18 16:48
Should be addressed in #138

**Closed** 2016-04-26 21:31 UTC
